# Generated by Django 4.2.7 on 2023-11-15 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WifiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=255)),
                ('bssid', models.CharField(max_length=255)),
                ('authType', models.CharField(max_length=255)),
                ('signalStrength', models.CharField(max_length=255)),
                ('connectionScore', models.IntegerField()),
                ('networkHash', models.CharField(max_length=255)),
            ],
        ),
    ]
